# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on: workflow_dispatch

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish 
      run: dotnet publish --runtime win-x64 --self-contained -p:PublishProfile=FolderWindows
    - name: Publish 
      run: dotnet publish --runtime linux-x64 --self-contained -p:PublishProfile=FolderLinux
    - name: Upload a Build Artifact for Windows
      uses: actions/upload-artifact@v3
      with:
        name: win-x64
        path: src/Bookmarks/bin/publish/win-x64/**
        if-no-files-found: error
    - name: Upload a Build Artifact for Linux
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: src/Bookmarks/bin/publish/linux-x64/**
        if-no-files-found: error      
